name: genem_env
channels:
  - defaults
  - conda-forge
  - cantera
  - anaconda
dependencies:
  - RDKit
  - random
  - logging
  - numpy
  - sascorer.py from SAScore repository on github
  - fpscores.pkl.gz from SAScore repository on github
