name: CI Pipeline

on:
  pull_request:
    branches: [master]

jobs:
  conda-tests:
    name: Conda Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniconda-version: latest
          activate-environment: gen_em
          environment-file: environment.yml
          conda-solver: libmamba

      - name: Run Unit Tests
        run: make test

      - name: Collect Logs on Failure
        if: failure()
        run: |
          echo "Tests failed. Please check the logs for details."
