name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  conda-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: genem_env
          miniconda-version: latest
          conda-solver: libmamba

      - name: Run Unit Tests
        run: python -m unittest

      - name: Collect Logs on Failure
        if: failure()
        run: |
          echo "Tests failed. Please check the logs for details."
